name: Ubuntu ARM64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v2
      with:
       repository: alcz/hbpksrc
       path: hbpksrc

    - name: Prepare environment
      run: |
        sudo apt install libcurl4-openssl-dev libssl-dev
        sudo mkdir /opt/hbpk
        sudo chown $USER:$USER /opt/hbpk

    - name: Build base of hbpk
      run: |
        export PATH="/opt/hbpk/bin:$PATH"
        cd hbpksrc/base
        mv xz xz-old
        mv xz-current xz
        make install
        rm /opt/hbpk/bin/hbpk-sizecat # pacify progress-bar
        ln -s /usr/bin/cat /opt/hbpk/bin/hbpk-sizecat
        cat /opt/hbpk/bin/hbpk-del | sed -e 's/hbpk-sizecat -nosize/cat/' > /tmp/hbpk-del
        mv /tmp/hbpk-del /opt/hbpk/bin/hbpk-del # another patch for extra argument
        chmod 755 /opt/hbpk/bin/hbpk-del

    - name: Build a selection of packges
      run: |
        export PATH="/opt/hbpk/bin:/opt/hbpk/harbour/bin/linux/zig:$PATH"
        cd hbpksrc/build
        PKGSELECTION=zig-binary make install
        PKGSELECTION=harbour-core make install
        cd ../harbour-core-onedir
        mv ../harbour-core/harbour-* ./ # only redo the install
        touch .config .depend .extract .fetch .patch
        cd ..
        PKGSELECTION=harbour-core-onedir make install
        PKGSELECTION=" \
          letodbf-server-elch \
          letodbf-server-alcz \
          letodbf-rdd-elch \
          letodbf-rdd-alcz \
          libpq9 \
          harbour-pgsql \
          " \
        make install

    - name: Run tests
      run: |
        /opt/hbpk/harbour/bin/linux/zig/hbtest

    - name: Rename artifacts
      run: |
        cd hbpksrc
        mv packages packages-aarch64-linux-musl

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-aarch64-linux-musl
        path: hbpksrc/packages-aarch64-linux-musl/*
