name: Windows 64-bit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Init MSYS2
      uses: msys2/setup-msys2@v2
      with:
        location: d:/
        update: true
        install: >
          mingw-w64-x86_64-bzip2
          mingw-w64-x86_64-xz
          mingw-w64-x86_64-minizip
          mingw-w64-x86_64-make
          unzip
          patch
          diffutils
          make

    - uses: actions/checkout@v2
      with:
       repository: alcz/hbpksrc
       path: hbpksrc

    - name: Prepare environment
      shell: msys2 {0}
      run: |
        mkdir /opt/hbpk

    - name: Build base of hbpk
      shell: msys2 {0}
      run: |
        export PATH="/opt/hbpk/bin:/usr/bin:$PATH"
        export HBPK_BOOTCAT=no # shouldn't build hbpk-sizecat in CI at all
        cd hbpksrc/base
        mv xz xz-old
        mv xz-inherit xz
        make install
        cat /opt/hbpk/bin/hbpk-del | sed -e 's/hbpk-sizecat -nosize/cat/' > /tmp/hbpk-del
        mv /tmp/hbpk-del /opt/hbpk/bin/hbpk-del # another patch for extra argument
        chmod 755 /opt/hbpk/bin/hbpk-del
        ln -f -s /usr/bin/cat.exe /opt/hbpk/bin/hbpk-sizecat.exe

    - name: Build a selection of packges
      shell: msys2 {0}
      run: |
        export PATH="/opt/hbpk/bin:/opt/hbpk/harbour/bin/win/zig:$PATH"
        cd hbpksrc/build
        PKGSELECTION=zig-binary make install
        PKGSELECTION=harbour-core make install
        cd harbour-core-onedir
        mv ../harbour-core/harbour-* ./ # only redo the install
        touch .config .depend .extract .fetch .patch
        cd ..
        PKGSELECTION=harbour-core-onedir make install
        PKGSELECTION=" \
          letodbf-server-elch \
          letodbf-server-alcz \
          letodbf-rdd-elch \
          letodbf-rdd-alcz \
          libpq9 \
          harbour-pgsql \
          " \
        make install

    - name: Run tests
      shell: msys2 {0}
      run: |
        /opt/hbpk/harbour/bin/win/zig/hbtest

    - name: Rename artifacts
      run: |
        cd hbpksrc
        mv packages packages-x86_64-windows-gnu

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-x86_64-windows-gnu
        path: hbpksrc/packages-x86_64-windows-gnu/*
